#!/usr/bin/env bash
# configed web-01 to have HTTP response header

# Update Packages installations
sudo apt-get update
sudo apt-get install -y nginx

# Created an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performed a redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/salifabu permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Created a 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# custom HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test for syntax errors
sudo nginx -t

# Restart nginx
sudo service nginx restart
