#!/usr/bin/env bash

# Update package lists and install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# HAProxy config files edit
server_config="

defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend Salifu_frontend
    bind *:80
    mode http
    default_backend Salifabu_backend

backend Salifabu_backend
    balance roundrobin
    server 440997-web-01 54.157.152.67:80 check
    server 440997-web-02 52.201.151.133:80 check
"

# Existing HAProxy configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# HAProxy config file
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg

# HAProxy to be started by the init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Test HAProxy for syntax errors
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
if [ $? -ne 0 ]; then
    echo "HAProxy configuration test failed. Please check the configuration."
    exit 1
fi

# Restart the HAProxy service
sudo service haproxy restart

# Check the status of the HAProxy service
sudo service haproxy status

echo "HAProxy has been installed and configured successfully."
